// app/layout.tsx

import localFont from 'next/font/local';
import './globals.css';

const kelsonSans = localFont({
  src: [
    {
      // relativně vůči app/layout.tsx → ../public/fonts/kelson/…
      path: '../public/fonts/kelson/KelsonSansRegular.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../public/fonts/kelson/KelsonSansBold.woff2',
      weight: '700',
      style: 'normal',
    },
  ],
  variable: '--font-kelson',
  display: 'swap',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`
          ${kelsonSans.variable}
          font-sans
          bg-[url('/imgs/hero.jpg')]
          bg-fixed
          bg-center
          bg-cover
        `}
      >
        {children}
      </body>
    </html>
  );
}
